src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $unitNumber;
    /**
     * @ORM\Column(type="integer")
     */
    private $unitPrice;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $soldUnit;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;
    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="products")
     */
    private $HisCategory;

    /**
     * @ORM\ManyToOne(targetEntity=TheBrand::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $hisBrand;

    /**
     * @ORM\OneToMany(targetEntity=SalesHistory::class, mappedBy="product")
     */
    private $salesHistories;



    public function __construct()
    {
        $this->HisCategory = new ArrayCollection();
        $this->salesHistories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUnitPrice(): ?int
    {
        return $this->unitPrice;
    }

    public function setUnitPrice(int $unitPrice): self
    {
        $this->unitPrice = $unitPrice;

        return $this;
    }

    public function getUnitNumber(): ?int
    {
        return $this->unitNumber;
    }

    public function setUnitNumber(int $unitNumber): self
    {
        $this->unitNumber = $unitNumber;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getHisCategory(): Collection
    {
        return $this->HisCategory;
    }

    public function addHisCategory(Category $hisCategory): self
    {
        if (!$this->HisCategory->contains($hisCategory)) {
            $this->HisCategory[] = $hisCategory;
        }

        return $this;
    }

    public function removeHisCategory(Category $hisCategory): self
    {
        $this->HisCategory->removeElement($hisCategory);

        return $this;
    }

    public function getHisBrand(): ?TheBrand
    {
        return $this->hisBrand;
    }

    public function setHisBrand(?TheBrand $hisBrand): self
    {
        $this->hisBrand = $hisBrand;

        return $this;
    }

    /**
     * @return Collection|SalesHistory[]
     */
    public function getSalesHistories(): Collection
    {
        return $this->salesHistories;
    }

    public function addSalesHistory(SalesHistory $salesHistory): self
    {
        if (!$this->salesHistories->contains($salesHistory)) {
            $this->salesHistories[] = $salesHistory;
            $salesHistory->setProduct($this);
        }

        return $this;
    }

    public function removeSalesHistory(SalesHistory $salesHistory): self
    {
        if ($this->salesHistories->removeElement($salesHistory)) {
            // set the owning side to null (unless already changed)
            if ($salesHistory->getProduct() === $this) {
                $salesHistory->setProduct(null);
            }
        }

        return $this;
    }

    public function getSoldUnit(): ?int
    {
        return $this->soldUnit;
    }

    public function setSoldUnit(?int $soldUnit): self
    {
        $this->soldUnit = $soldUnit;

        return $this;
    }
    public  function  getFormattedPrice():string{
        return number_format($this->getUnitPrice(),0,'',' ');
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('unitPrice')
            ->add('intNumber')
            ->add('createdAt')
            ->add('updatedAt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/product')]
class ProductController extends AbstractController
{

    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findProductsAvailable(),
        ]);
    }

    #[Route('/new', name: 'product_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('product/new.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'product_show', methods: ['GET'])]
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    #[Route('/{id}/edit', name: 'product_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'product_delete', methods: ['POST'])]
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('product_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
   <div class="jumbotron text-center">
       <h1>name</h1>
       <p>text</p>

   </div>
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('product_index') }}">back to list</a>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-8">

            </div>
            <div class="col-md-4">
                <h1>{{ product.name }}</h1>
                <h2>
                    {{ product.hisBrand }}
                </h2>
                <h3>
                    {% for cat in product.hisCategory %}
                        {{ cat.title }},
                    {% endfor %}
                </h3>
                <div class="text-primary" style="font-size: 4em;font-weight: bold;">{{ product.formattedPrice }}</div>
                <a href="#" class="btn btn-primary">Contacter l'agence</a>
            </div>
        </div>
    </div>
</div>
    <div class="container mt-4">

        <p>
            {{ product.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>specificité</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Unit Price</td>
                        <td>{{ product.unitPrice }}</td>
                    </tr>
                    <tr>
                        <td>Unit Number</td>
                        <td>{{ product.unitNumber }}</td>
                    </tr>
                    <tr>
                        <td>Created At</td>
                        <td>{{ product.unitNumber }}</td>
                    </tr>
                    <tr>
                        <td>Updated At</td>
                        <td>{{ product.unitNumber }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}